version: '3'
services:
  apigateway:
    image: gwangjang/apigateway
    networks:
      - msa-network

  eureka:
    image: gwangjang/eureka:latest
    networks:
      - msa-network

  community:
    image: gwangjang/community
    depends_on:
      - eureka
      - apigateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    ports:
      - 8082:8082
    networks:
      - msa-network
    build: ./CommunityService

networks:
  msa-network:
