community:
    image: gwangjang/community
    depends_on:
      - eureka
      - apigateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    ports:
      - 8082:8082
    networks:
      - msa-network
    build: ./CommunityService

